apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /alpha(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: alpha-service
                port:
                  number: 80
          - path: /beta(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: beta-service
                port:
                  number: 80
