apiVersion: v1
kind: Service
metadata:
  name: alpha-service
spec:
  selector:
    app: alpha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: beta-service
spec:
  selector:
    app: beta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
